title: Programming Notes
email: lowcloudnine at hotmail dot com
description: >- # this means to ignore newlines until "baseurl:"
  A place for links, notes, advice and procedures I use or have found useful.

# baseurl: "" # the subpath of your site, e.g. /blog
# url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: lowcloudnine
github_username:  lowcloudnine

# Build settings
# markdown: kramdown
theme: minima
# plugins:
# - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
